steps:
  # Install
  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['ci', '--no-audit', '--no-fund']

  # Lint
  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['run', 'lint']

  # Test
  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['run', 'test']

  # Build
  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Bucket Sync - Add env. variable to hide bucket name
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args: ['gsutil', 'cp', '-r', 'dist/*', 'gs://bmendoza.io']
