steps:
# Install
  - name: 'node:lts-alpine'
    entrypoint: "npm"
    args: ['ci', '--no-audit', '--no-funding']

# Lint
  - name: 'node:lts-alpine'
    entrypoint: "npm"
    args: ['run', 'lint']

# Test
  - name: 'node:lts-alpine'
    entrypoint: "npm"
    args: ['run', 'test']

# Build
  - name: 'node:lts-alpine'
    entrypoint: "npm"
    args: ['run', 'build']

# Set GCP Project - Actualizar a env variable para quitar projectId del yaml
  - name: 'https://gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args: ["gcloud", 'config', 'set', 'project', 'paybotic-example-setup']

# Hosting - Actualizar a env variable para quitar bucket name del yaml
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args: ["gsutil", "rm", "-a", "gs://example-hosting-paybotic/**"]

# Bucket Sync - Actualizar a env variable para quitar bucket name del yaml
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args: ["gsutil", 'cp', '-r', 'dist/*', 'gs://example-hosting-paybotic']
